language: c

# Platform descriptions
# NOTE: These can be used in creating the build matrix by making use of the
#       anchor/alias YAML features.
linux_gcc8: &linux_gcc8
  os: linux
  dist: xenial
  compiler: gcc
  addons:
    apt:
      update: true
      sources: [ ubuntu-toolchain-r-test ]
      packages: [ gcc-8 g++-8 ]

linux_clang: &linux_clang
  os: linux
  dist: xenial
  compiler: clang
  addons:
    apt:
      update: true

osx_xcode10_1: &osx_xcode10_1
  os: osx
  osx_image: xcode10.1
  compiler: clang
  addons:
    homebrew:
      packages:
      - pyenv-virtualenv

windows_vs2017: &windows_vs2017
  os: windows

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "E/qGuqxZVZlHRuAfiAQ2PfP9PGH6rLKdKf+lvEu+vT/1r1XL7nf5xwM99+HKg0bx6s9ME+mIVD/6XODc7qwe2P+H/ufh8Q2s2jsTOP8bASpmseiDo3BtC7d6O9RIIvZoLzAqgcri8madRl66Bhs6RnjxIfRRL0GWYcrfbsTypvCnKg0B37300NwtPksMISiuuXdhkHzqJ8Q3Css2qfsMnCaQSeg8md4/gwdnldS6PbbMxhNR3wp3STzAVlhIns5FmVcySGKwhZGfpAE4khGQWfpJUGDQSE2kuBhmR0QuRULwtbh3q5kM7KJRAzlmHvZ4RZVuVA5pSWcD8uSrnTMSLxvjodzvjcWY0b7mH9IE60RqCRePWblw1d4QVOyToeC7EZD5+ZetpKf/2dG8K8rpn3G+yrixxoW22A37c1UBNI+Ny5u6drPnXy4kX/qKs5Mi1i+LcWilsKxHfO27G0zbr+XEOlZ9szqb3/yHrlXjBzos5kzECB2yIAyiMiIx0iG4e9+LPUwSdgRlTmTPd5f1cY4Dyw5HirmAJzMd1x+zJu5DZD+Mf40y6PO9Y7zThK9kSC/h3PFVsCt1eF44xUBk/lWosbSJanvWTKmKSKoveK4a1cYESdFewJVoaZXXtYzHAOzSUtzqt/Y8TKfoUv8poJfHxKThp5OFPf+hEb6SZX0="

matrix:
  include:
    - <<: *linux_gcc8
      env: [ BUILD_TYPE=Release, C_COMPILER=gcc-8, CXX_COMPILER=g++-8, USE_SANITIZER=none, COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG", COVERITY_SCAN_BRANCH_PATTERN="coverity_scan", COVERITY_SCAN_NOTIFICATION_EMAIL="thijs.sassen@adlinktech.com",COVERITY_SCAN_BUILD_COMMAND_PREPEND="cov-configure --comptype gcc --compiler gcc-8 --template", COVERITY_SCAN_BUILD_COMMAND="cmake --build ."]
    - <<: *linux_gcc8
      env: [ BUILD_TYPE=Debug, C_COMPILER=gcc-8, CXX_COMPILER=g++-8, USE_SANITIZER=none ]
    - <<: *linux_gcc8
      env: [ BUILD_TYPE=Release, C_COMPILER=gcc-8, CXX_COMPILER=g++-8, USE_SANITIZER=none ]
    - <<: *linux_clang
      env: [ BUILD_TYPE=Debug, C_COMPILER=clang, CXX_COMPILER=clang++, USE_SANITIZER=address ]
    - <<: *linux_clang
      env: [ BUILD_TYPE=Release, C_COMPILER=clang, CXX_COMPILER=clang++, USE_SANITIZER=none ]
    - <<: *osx_xcode10_1
      env: [ BUILD_TYPE=Debug, C_COMPILER=clang, CXX_COMPILER=clang++, USE_SANITIZER=address ]
    - <<: *osx_xcode10_1
      env: [ BUILD_TYPE=Release, C_COMPILER=clang, CXX_COMPILER=clang++, USE_SANITIZER=none ]
    - <<: *windows_vs2017
      env: [ ARCH=x86, BUILD_TYPE=Debug, GENERATOR="Visual Studio 15 2017" ]
    - <<: *windows_vs2017
      env: [ ARCH=x86_64, BUILD_TYPE=Debug, GENERATOR="Visual Studio 15 2017" ]
    - <<: *windows_vs2017
      env: [ ARCH=x86_64, BUILD_TYPE=Release, GENERATOR="Visual Studio 15 2017" ]

# Conan will automatically determine the best compiler for a given platform
# based on educated guesses. The first check is based on the CC and CXX
# environment variables, the second (on Windows) is to check if Microsoft
# Visual Studio is installed. On Travis CC and CXX are set to gcc on Microsoft
# Windows targets as well, this has the undesired effect that MSVC is not
# detected, unsetting CC and CXX solves that problem.
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      eval "unset CC";
      eval "unset CXX";
      JAVA_HOME=$(find "/c/Program Files/Android/jdk/" -name "*openjdk*" | sort | head -n 1);
      export JAVA_HOME;
      export PATH="${PATH}:${JAVA_HOME}/bin";
    else
      eval "export CC=${C_COMPILER}";
      eval "export CXX=${CXX_COMPILER}";
    fi
# Windows targets in Travis are still very much in beta and Python is not yet
# available and installation of Python through Chocolaty does not work well.
# The real fix is to wait until Python and pip are both available on the
# target. Until then download Conan from the official website and simply add
# the extracted folder to the path.
install:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      choco install innoextract;
      choco install maven --ignore-dependencies;
      wget -q https://dl.bintray.com/conan/installers/conan-win-64_1_10_0.exe;
      innoextract conan-win-64_1_10_0.exe;
      eval "export PATH=\"$(pwd)/app/conan:${PATH}\"";
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      eval "$(pyenv init -)";
      pyenv virtualenv conan;
      pyenv rehash;
      pyenv activate conan;
      pip install conan --upgrade;
    else
      pip install conan --upgrade --user;
    fi
  - conan profile new default --detect

before_script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan profile get settings.arch default
  - if [ -z "${ARCH}" ]; then
      eval "export ARCH=\"$(conan profile get settings.arch default)\"";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      GENERATOR_ARCH=$(if [ "${ARCH}" = "x86_64" ]; then echo " Win64"; fi);
      eval "export GENERATOR=\"${GENERATOR}${GENERATOR_ARCH}\"";
      eval "export USE_SANITIZER=none";
    else
      eval "export GENERATOR=\"Unix Makefiles\"";
    fi
  - export

script:
  - mkdir build
  - cd build
  - conan install -b missing -s arch=${ARCH} -s build_type=${BUILD_TYPE} ..
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
          -DCMAKE_INSTALL_PREFIX=$(pwd)/install
          -DUSE_SANITIZER=${USE_SANITIZER}
          -DBUILD_TESTING=on
          -G "${GENERATOR}" ../src
  - if [[ -n $COVERITY_SCAN_PROJECT_NAME ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi
  - cmake --build . --config ${BUILD_TYPE} --target install
  - CYCLONEDDS_URI='<CycloneDDS><DDSI2E><Internal><EnableExpensiveChecks>all</EnableExpensiveChecks></Internal></DDSI2E></CycloneDDS>' ctest -T test -C ${BUILD_TYPE}
  - if [ "${USE_SANITIZER}" != "none" ]; then
      CMAKE_LINKER_FLAGS="-DCMAKE_LINKER_FLAGS=-fsanitize=${USE_SANITIZER}";
      CMAKE_C_FLAGS="-DCMAKE_C_FLAGS=-fsanitize=${USE_SANITIZER}";
    fi
  - mkdir install/share/CycloneDDS/examples/helloworld/build
  - cd install/share/CycloneDDS/examples/helloworld/build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
          ${CMAKE_C_FLAGS}
          ${CMAKE_LINKER_FLAGS}
          -G "${GENERATOR}" ..
  - cmake --build . --config ${BUILD_TYPE}

